baseURL: https://cv-juanpacheco.netlify.app
languageCode: en
title: ''
theme: hugo-devresume-theme
googleAnalytics: UA-XXXXXXX-Y
params:
  author: Juan Pacheco

  contact:
    enable: yes
    list:
      - icon: fas fa-phone-square
        text: +593 960 659 647
        url: tel:#
      - icon: fas fa-envelope-square
        text: juanalfred16@hotmail.com
        url: mailto:#
      - icon: fas fa-globe
        text: https://juanpacheco.netlify.app/
        url: '#'
    location: Ecuador
  description: DevResume - Bootstrap 4 Resume/CV Template For Software Developers
  education:
    enable: yes
    list:
      - dates: 2021 - 2022
        degree: MSc in Applied Economics
        university: Torcuato Di Tella
      - dates: 2015 - 2020
        degree: BSc in Economics
        university: Escuela Superior Politécnica del Litoral 
  experience:
    enable: yes
    list:
      - company: Naportec, Dole
        dates: 2019 - 2020
        
        items:
          - details:Perform routine calculations to produce analyses and reports as requested by the finance director.
          - details: Create, send, and follow up on invoices.
          - details: Reconcile any discrepancies or errors identified by conversing with employees and/or clients.
          - details: Collect and enter data for various financial spreadsheets.
        title: Finance Assistant
      - company: Naportec, Dole
        dates: March 2018 - May 2018
       
      
  information:
    enable: yes
    list:
      - items:
          - details: 2020 · Desafíos en el pronóstico de los ingresos tributarios en el Ecuador en tiempos de pandemia SARS COVID-19 periodo 2020-2021
          
        title: Degree works
      - details: Climbing, Snowboarding, Photography, Travelling
        title: Interests
  interests:
    enable: yes
    list:
      - name: Macroeconomics
      - name: Financial Econometrics
      - name: Econometrics
      - name: Data Analysis
  languages:
    enable: yes
    list:
      - level: B2
        name: English
      - level: Native
        name: Spanish
      - level: C2
        name: Portuguese
  primaryColor: '#54B689'
  profile:
    avatar: avatar.png
    enable: yes
    name: Juan Pacheco
    tagline: Economics 
  projects:
    enable: yes
    list:
      - meta: Open Source
        tagline: You can use this section for your side projects. Lorem ipsum dolor
          sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
          Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes,
          nascetur ridiculus mus.
        title: Project Lorem Ipsum
      - meta: Open Source
        tagline: You can use this section for your side projects. Cras dapibus. Vivamus
          elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula,
          porttitor eu, consequat vitae, eleifend ac, enim.
        title: Project Sed Fringilla
      - meta: Open Source
        tagline: You can use this section for your side projects. Cras dapibus. Vivamus
          elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula,
          porttitor eu, consequat vitae, eleifend ac, enim.
        title: Project Praesent
  skills:
    enable: yes
    list:
      - items:

          - details: Python/R/MATLAB/Stata
         
        title: Technical
      - items:
          - details: Effective communication
          - details: Team player
          - details: Strong problem solver
          - details: Good time management
        title: Professional
  social:
    enable: yes
    list:
      - icon: fab fa-github-square
        title: jalfred714
        url: https://github.com/jalfred714
      - icon: fab fa-linkedin
        title: juan-pacheco-314263111
        url: https://www.linkedin.com/in/juan-pacheco-314263111
      - icon: fab fa-twitter-square
        title: '@jalfred7'
        url: https://twitter.com/Jalfred7
  summary:
    enable: yes
    text: I'm an economist with multiple skills in data analysis  and strong background in econometrics and macroeconomics. 
  textPrimaryColor: '#292929'
